name: "Twasi Custom Variables"
main: net.twasiplugin.customvariables.CustomVariablePlugin
version: 1.0-SNAPSHOT
author: Twasi-Team

commands:
  - variable
  - var

permissions:
  - net.twasi.variables.update
  - net.twasi.variables.create
  - net.twasi.variables.delete