name: "customvariables"
main: "net.twasiplugin.customvariables.CustomVariablePlugin"
version: "1.0-SNAPSHOT"
author: "Twasi-Team"

commands:
  - setvar
  - delvar

permissions:
  - "net.twasi.variables.update"
  - "net.twasi.variables.create"
  - "net.twasi.variables.delete"

api: |
  type VariableCollection {
    variableByName(varName: String): Variable,
    allVariables: [Variable],
    addVariable(name: String, output: String): Boolean,
    removeVariableByName(name: String): Boolean,
    renameVariable(name: String, newName: String): Boolean
  }

  type Variable {
    name: String,
    output: String
  }