name: "CustomVariables"
main: "net.twasiplugin.customvariables.CustomVariablePlugin"
version: "1.0"
author: "Twasi-Team"

commands:
  - setvar
  - delvar

permissions:
  - "net.twasi.variables.update"
  - "net.twasi.variables.create"
  - "net.twasi.variables.delete"

api: |
  type CustomVariables {
    variableByName(varName: String): Variable,
    allVariables: [Variable],
    addVariable(name: String, output: String): Boolean,
    removeVariable(id: String): Boolean,
    editVariable(id: String, name: String, output: String): Boolean
  }

  type Variable {
    id: String,
    name: String,
    output: String
  }